services:
  shortener:
    container_name: 'shortener'
    build: .
    depends_on:
      - cache
    ports:
      - "4899:4899"
    environment: &env
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_USER: default
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - ./logs:/opt/shortener/logs
    configs:
      - source: shortener_config
        target: /opt/shortener/config.json
  cache:
    image: redis:6.2-alpine
    restart: always
    environment: *env
    command: sh -c 'redis-server --save 20 1 --loglevel warning --requirepass "$$REDIS_PASSWORD"'
    volumes: 
      - cache:/data

volumes:
  cache:
    driver: local

configs:
  shortener_config:
    file: ./config.json
